/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import dao.NhanVien_DAO;
import dao.SanPham_DAO;
import entity.CapDoHoc;
import entity.ChucVu;
import entity.KhachHang;
import entity.LoaiBia;
import entity.LoaiSanPham;
import entity.NhaCungCap;
import entity.NhaXuatBan;
import entity.NhanVien;
import entity.Sach;
import entity.TacGia;
import entity.TaiKhoan;

/**
 *
 * @author Graviss
 */
public class GD_QuanLyNhanVien extends javax.swing.JPanel {

	/**
	 * Creates new form GD_QuanLyNhanVien
	 */
	public GD_QuanLyNhanVien() {
		initComponents();
		loadnv();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroupgt = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		txttimkiem = new javax.swing.JTextField();
		btntimkiem = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablenv = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		lblma = new javax.swing.JLabel();
		txtma = new javax.swing.JTextField();
		lblhoten = new javax.swing.JLabel();
		txthoten = new javax.swing.JTextField();
		lblngaysinh = new javax.swing.JLabel();
		jdcngaysinh = new com.toedter.calendar.JDateChooser();
		lblcccd = new javax.swing.JLabel();
		txtcccd = new javax.swing.JTextField();
		lbldiachi = new javax.swing.JLabel();
		txtdiachi = new javax.swing.JTextField();
		lblsdt = new javax.swing.JLabel();
		txtsdt = new javax.swing.JTextField();
		lblgioitinh = new javax.swing.JLabel();
		lblchucvu = new javax.swing.JLabel();
		lbltaikhoan = new javax.swing.JLabel();
		txttaikhoan = new javax.swing.JTextField();
		lblmatkhau = new javax.swing.JLabel();
		txtmatkhau = new javax.swing.JTextField();
		cbbchucvu = new javax.swing.JComboBox<>();
		btnthem = new javax.swing.JButton();
		btnxoa = new javax.swing.JButton();
		btnsua = new javax.swing.JButton();
		radnam = new javax.swing.JRadioButton();
		radnu = new javax.swing.JRadioButton();
		txtthongbao = new javax.swing.JLabel();
		modelCbocv = new DefaultComboBoxModel<ChucVu>();
		cbbchucvu.setEditable(true);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setPreferredSize(new java.awt.Dimension(600, 540));

		txttimkiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txttimkiemActionPerformed(evt);
			}
		});

		btntimkiem.setText("Tìm kiếm");
		btntimkiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btntimkiemActionPerformed(evt);
			}
		});

		tablenv.setModel(modelnv = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "STT", "Mã", "Họ Tên", "Ngày Sinh", "CCCD", "Địa chỉ", "SĐT", "Giới Tính",
				"Tài Khoản", "Chức vụ" }));
		tablenv.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tablenvMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tablenv);
		if (tablenv.getColumnModel().getColumnCount() > 0) {
			tablenv.getColumnModel().getColumn(3).setResizable(false);
			tablenv.getColumnModel().getColumn(5).setResizable(false);
		}

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
						.addGap(18, 18, 18).addComponent(btntimkiem).addGap(50, 50, 50))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btntimkiem))
						.addGap(18, 18, 18).addComponent(jScrollPane1).addContainerGap()));

		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		lblma.setText("Mã:");

		txtma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtmaActionPerformed(evt);
			}
		});

		lblhoten.setText("Họ Tên:");

		lblngaysinh.setText("Ngày Sinh:");

		lblcccd.setText("CCCD:");

		lbldiachi.setText("Địa chỉ:");

		lblsdt.setText("SĐT:");

		lblgioitinh.setText("Giới Tính:");

		lblchucvu.setText("Chức vụ:");

		lbltaikhoan.setText("Tài Khoản:");

		lblmatkhau.setText("Mật Khẩu:");

		cbbchucvu.setModel(modelCbocv);
		cbbchucvu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbcvActionPerformed(evt);
			}
		});

		txtmatkhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtmatkhauActionPerformed(evt);
			}
		});

		btnthem.setText("Thêm");
		btnthem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnthemActionPerformed(evt);
			}
		});

		btnxoa.setText("Xóa");
		btnxoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnxoaActionPerformed(evt);
			}
		});

		btnsua.setText("Sửa");
		btnsua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnsuaActionPerformed(evt);
			}
		});

		buttonGroupgt.add(radnam);
		radnam.setText("Nam");

		buttonGroupgt.add(radnu);
		radnu.setText("Nữ");
		txtma.setEditable(false);
		txttaikhoan.setEditable(false);
		txtmatkhau.setEditable(false);
		btntimkiem.setFont(new Font("Serif", Font.PLAIN, 18));
		btnthem.setFont(new Font("Serif", Font.PLAIN, 18));
		btnxoa.setFont(new Font("Serif", Font.PLAIN, 18));
		btnsua.setFont(new Font("Serif", Font.PLAIN, 18));
		Font font1 = new Font("Serif", Font.PLAIN, 13);
		lblma.setFont(font1);
		lblhoten.setFont(font1);
		lblngaysinh.setFont(font1);
		lblcccd.setFont(font1);
		lbldiachi.setFont(font1);
		lblgioitinh.setFont(font1);
		lbltaikhoan.setFont(font1);
		lblmatkhau.setFont(font1);
		lblsdt.setFont(font1);
		lblchucvu.setFont(font1);
		jdcngaysinh.setDateFormatString("yyyy-MM-dd");
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(20, 20, 20)
										.addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addComponent(
												btnsua, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(18, 18, 18))
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblhoten, javax.swing.GroupLayout.PREFERRED_SIZE,
																51, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lblngaysinh).addComponent(lblcccd,
																javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lbldiachi, javax.swing.GroupLayout.PREFERRED_SIZE,
																56, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lblsdt, javax.swing.GroupLayout.PREFERRED_SIZE,
																56, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel2Layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																		txtsdt)
																.addComponent(txtdiachi).addComponent(txtcccd)
																.addComponent(jdcngaysinh,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(txthoten)))
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(
																		lblmatkhau,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(txtmatkhau,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 212,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(lbltaikhoan,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(txttaikhoan,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 212,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(lblgioitinh,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(24, 24, 24).addComponent(radnam)
																.addGap(18, 18, 18).addComponent(radnu))
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(lblchucvu,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(cbbchucvu,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 212,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGap(0, 0, Short.MAX_VALUE)))
												.addGap(3, 3, 3))
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(lblma, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtma))))
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(
										txtthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 275,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(14, 14, 14)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblma).addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblhoten).addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblngaysinh)
								.addComponent(jdcngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblcccd).addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbldiachi).addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblsdt).addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblgioitinh).addComponent(radnam).addComponent(radnu))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblchucvu).addComponent(cbbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbltaikhoan)
								.addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblmatkhau)
								.addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(txtthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnthem).addComponent(btnxoa).addComponent(btnsua))
						.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttimkiemActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txttimkiemActionPerformed

	private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void tablenvMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablenvMouseClicked
		// TODO add your handling code here:
		int row = tablenv.getSelectedRow();
		loadTbltoForm(row);
	}// GEN-LAST:event_tablenvMouseClicked

	private void cbcvActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btntimkiemActionPerformed
		// TODO add your handling code here:
		timKiem();
	}// GEN-LAST:event_btntimkiemActionPerformed

	private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnthemActionPerformed
		// TODO add your handling code here:
		setEditableForm(true);
		them_nv();
	}// GEN-LAST:event_btnthemActionPerformed

	private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnxoaActionPerformed
		// TODO add your handling code here:
		setEditableForm(true);
		xoa();
	}// GEN-LAST:event_btnxoaActionPerformed

	private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnsuaActionPerformed
		// TODO add your handling code here:
		setEditableForm(true);
		suanv();
	}// GEN-LAST:event_btnsuaActionPerformed

	private void txtmatkhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtmatkhauActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtmatkhauActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnsua;
	private javax.swing.JButton btnthem;
	private javax.swing.JButton btntimkiem;
	private javax.swing.JButton btnxoa;
	private javax.swing.ButtonGroup buttonGroupgt;
	private javax.swing.JComboBox<ChucVu> cbbchucvu;
	private DefaultComboBoxModel<ChucVu> modelCbocv;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private com.toedter.calendar.JDateChooser jdcngaysinh;
	private javax.swing.JLabel lblcccd;
	private javax.swing.JLabel lblchucvu;
	private javax.swing.JLabel lbldiachi;
	private javax.swing.JLabel lblgioitinh;
	private javax.swing.JLabel lblhoten;
	private javax.swing.JLabel lblma;
	private javax.swing.JLabel lblmatkhau;
	private javax.swing.JLabel lblngaysinh;
	private javax.swing.JLabel lblsdt;
	private javax.swing.JLabel lbltaikhoan;
	private javax.swing.JRadioButton radnam;
	private javax.swing.JRadioButton radnu;
	private javax.swing.JTable tablenv;
	private javax.swing.JTextField txtcccd;
	private javax.swing.JTextField txtdiachi;
	private javax.swing.JTextField txthoten;
	private javax.swing.JTextField txtma;
	private javax.swing.JTextField txtmatkhau;
	private javax.swing.JTextField txtsdt;
	private javax.swing.JTextField txttaikhoan;
	private javax.swing.JLabel txtthongbao;
	private javax.swing.JTextField txttimkiem;
	// End of variables declaration                   
	private DefaultTableModel modelnv;
	private NhanVien_DAO nv_dao = new NhanVien_DAO();
	private ArrayList<NhanVien> dsnv = new ArrayList<NhanVien>();
	private int stt = 0;
	private int check = 0;

	private void loadnv() {
		while (tablenv.getRowCount() != 0) {
			modelnv.removeRow(0);
		}
		NhanVien_DAO nv = new NhanVien_DAO();
		String gt;
		dsnv = nv.getAllNV();
		for (NhanVien nhanvien : dsnv) {
			if (nhanvien.isGioiTinh() == false) {
				gt = "Nữ";
			} else
				gt = "Nam";
			Object row[] = { ++stt, nhanvien.getMaNV(), nhanvien.getHoTen(), nhanvien.getNgaySinh(), nhanvien.getCccd(),
					nhanvien.getDiaChi(), nhanvien.getSdt(), gt, null, nhanvien.getChucVu() };
			modelnv.addRow(row);
		}
		loadData();
	}

	public void loadData() {
		modelCbocv.addAll(nv_dao.getchucvu());

	}

	public void loadTbltoForm(int row) {
		System.out.println(row);
		NhanVien nv = dsnv.get(row);
		txtma.setText(nv.getMaNV());
		txthoten.setText(nv.getHoTen());
		java.util.Date ngaySinh = null;
		try {
			ngaySinh = new SimpleDateFormat("yyyy-MM-dd").parse(tablenv.getValueAt(row, 3).toString());
		} catch (Exception e) {
			// TODO: handle exception
		}
		jdcngaysinh.setDate(ngaySinh);
		txtcccd.setText(nv.getCccd());
		txtdiachi.setText(nv.getDiaChi());
		txtsdt.setText(nv.getSdt());
		if (tablenv.getValueAt(row, 7).toString().equals("Nam"))
			radnam.setSelected(true);
		else
			radnu.setSelected(true);
		cbbchucvu.setSelectedItem(nv.getChucVu());
		TaiKhoan tk = nv_dao.timTK(nv.getMaNV());
		txttaikhoan.setText(tk.getTenTK());
		txtmatkhau.setText(tk.getMatKhau());
		setEditableForm(true);
	}

	public void setEditableForm(boolean st) {
		txtma.setEditable(st);
		txthoten.setEditable(st);
		jdcngaysinh.setEnabled(st);
		txtcccd.setEditable(st);
		txtdiachi.setEditable(st);
		txtsdt.setEditable(st);
		radnam.setEnabled(st);
		radnu.setEnabled(st);
		cbbchucvu.setEnabled(st);
		txttaikhoan.setEnabled(st);
		txtmatkhau.setEnabled(st);

	}

	public void them_nv() {
		if (check != 1) {
			btnxoa.setText("Huỷ");
			btnsua.setEnabled(false);
			check = 1;
		} else {
//			checkThongTin();
			if (checkThongTin()) {
				String hoten = txthoten.getText();
				String diachi = txtdiachi.getText();
				String sdt = txtsdt.getText();
				boolean gt = radnam.isSelected() ? true : false;
				Date ns = Date.valueOf(((JTextField) jdcngaysinh.getDateEditor().getUiComponent()).getText());
				String cccd = txtcccd.getText();
				ChucVu cv = (ChucVu) cbbchucvu.getSelectedItem();
				NhanVien nv = new NhanVien(hoten, cccd, diachi, sdt, ns, gt, cv);
				if (nv_dao.timKiemNVTheoCCCD(cccd) == null) {
					try {
						nv_dao.addNV(nv);
						String maNV = nv_dao.timKiemNVTheoCCCD(cccd).getMaNV();
						nv_dao.themTK(maNV);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					reload();
					JOptionPane.showMessageDialog(null, "Thêm thành công");
					TaiKhoan tk = nv_dao.timTK(nv_dao.timKiemNVTheoCCCD(cccd).getMaNV());
					JOptionPane.showMessageDialog(null,
							"Tài khoản: " + tk.getTenTK() + " Mật khẩu: " + tk.getMatKhau());
					modelnv.setRowCount(0);
					stt = 0;
					loadnv();
				} else {
					JOptionPane.showMessageDialog(null, "Nhân viên này đã tồn tại");
				}
			}
		}
		// End of variables declaration//GEN-END:variables
	}

	public void xoa() {
		if (btnxoa.getText().equals("Huỷ") && check == 1) {
			xoatrang();
			setEditableForm(false);
			txtthongbao.setText("");
			btnxoa.setText("Xóa");
			btnsua.setEnabled(true);
			check = 0;
		} else if (btnxoa.getText().equals("Huỷ") && check == 2) {
			xoatrang();
			setEditableForm(false);
			txtthongbao.setText("");
			btnxoa.setText("Xóa");
			btnthem.setEnabled(true);
			check = 0;
		} else {
			int row = tablenv.getSelectedRow();
			if (row == -1) {
				txtthongbao.setText("Vui lòng chọn dòng cần xoá");
				return;
			}
			String ma = txtma.getText();
			NhanVien nv = new NhanVien(ma);
			if (JOptionPane.showConfirmDialog(null, "Xác nhận xóa") == JOptionPane.YES_OPTION) {
				try {
					nv_dao.xoa_NV(ma);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
//			modelNCC.removeRow(row);
				xoatrang();
			}

			modelnv.setRowCount(0);
			stt = 0;
			loadnv();
		}
	}

	public void xoatrang() {
		txtma.setText("");
		txthoten.setText("");
		txtcccd.setText("");
		txtdiachi.setText("");
		txtsdt.setText("");
		txttaikhoan.setText("");
		txtmatkhau.setText("");
		radnam.setSelected(true);
		cbbchucvu.setSelectedItem(null);
	}

//	public void suanv() {
//		String ma = txtma.getText();
//		String ten = txthoten.getText();
//		String cccd = txtcccd.getText();
//		String diachi = txtdiachi.getText();
//		ChucVu chucvu = (ChucVu) cbbchucvu.getSelectedItem();
//		Date ns = Date.valueOf(((JTextField) jdcngaysinh.getDateEditor().getUiComponent()).getText());
//		Boolean gt = radnam.isSelected() ? true : false;
//		String sdt = txtsdt.getText();
//		NhanVien nv = new NhanVien(ma, ten, cccd, diachi, sdt, ns, gt, chucvu);
//		try {
//			NhanVien_DAO nhanvien_DAO = new NhanVien_DAO();
//			nhanvien_DAO.suanv(nv);
//			;
//			loadnv();
//		} catch (Exception e) {
//			// TODO: handle exception
//			e.printStackTrace();
//		}
//	}
	public void suanv() {
		if (check != 2) {
			btnxoa.setText("Huỷ");
			btnthem.setEnabled(false);
			check = 2;
			setEditableForm(true);
		} else {
			int row = tablenv.getSelectedRow();
			if (row == -1) {
				JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần sửa");
				return;
			}
			checkThongTin();
			if (checkThongTin()) {
				String ma = txtma.getText();
				String sdt = txtsdt.getText();
				boolean gt = radnam.isSelected() ? true : false;
				String dc = txtdiachi.getText();
				Date ns = Date.valueOf(((JTextField) jdcngaysinh.getDateEditor().getUiComponent()).getText());
				String ten = txthoten.getText();
				String cccd = txtcccd.getText();
				ChucVu cv = (ChucVu) cbbchucvu.getSelectedItem();
				NhanVien nv = new NhanVien(ma, ten, cccd, dc, sdt, ns, gt, cv);
				try {
					nv_dao.suanv(nv);
					JOptionPane.showMessageDialog(null, "Sửa thông tin thành công");
				} catch (Exception e) {
				}
				modelnv.setRowCount(0);
				stt = 0;
				loadnv();
				xoatrang();
				reload();
			}
		}
	}

	// regest
	public boolean checkThongTin() {
		String ten = txthoten.getText();
		String dc = txtdiachi.getText();
		String sdt = txtsdt.getText();
		String cccd = txtcccd.getText();
		String today = Date.valueOf(LocalDate.now()).toString();
		if (ten.equals("")) {
			txtthongbao.setText("Nhập họ tên Nhân viên");
			return false;
		}
		if (jdcngaysinh.getDate() == null) {
			txtthongbao.setText("Nhập ngày sinh Nhân Viên");
			return false;
		}
		if (dc.equals("")) {
			txtthongbao.setText("Nhập địa chỉ Nhân Viên");
			return false;
		}
		if (!sdt.matches("[0-9]{10}")) {
			txtthongbao.setText("SĐT có 10 số và bắt đầu bằng 0");
			return false;
		}
		if (cccd.equals("")) {
			txtthongbao.setText("Nhập số CCCD Nhân viên");
			return false;
		}
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		String ns = dateFormat.format(jdcngaysinh.getDate());
		int a = ns.compareTo(today);
		System.out.println(a);
		if (a > 0) {
			txtthongbao.setText("Ngày sinh phải bé hơn ngày hiện tại");
			return false;
		}
		return true;
	}

	public void reload() {
		btnthem.setText("Thêm");
		btnxoa.setText("Xoá");
		btnsua.setText("Sửa");
		btnthem.setEnabled(true);
		btnxoa.setEnabled(true);
		btnsua.setEnabled(true);
		check = 0;
	}

	private void timKiem() {
		String tk = txttimkiem.getText();
		if (!tk.equals("")) {
			ArrayList<NhanVien> dsnv = nv_dao.timKiemNV(tk);
			LoadTimKiem(dsnv);
		}
		else {
			loadnv();
		}
	}

	private void LoadTimKiem(ArrayList<NhanVien> dsnv) {
		modelnv.setRowCount(0);
		String gt;
		for (NhanVien nhanvien : dsnv) {
			if (nhanvien.isGioiTinh() == false) {
				gt = "Nữ";
			} else
				gt = "Nam";
			Object row[] = { ++stt, nhanvien.getMaNV(), nhanvien.getHoTen(), nhanvien.getNgaySinh(), nhanvien.getCccd(),
					nhanvien.getDiaChi(), nhanvien.getSdt(), gt, null, nhanvien.getChucVu() };
			modelnv.addRow(row);
		}
		loadData();
	}
}
