/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import dao.NhanVien_DAO;
import entity.ChucVu;
import entity.NhanVien;

/**
 *
 * @author Graviss
 */
public class GD_QuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form GD_QuanLyNhanVien
     */
    public GD_QuanLyNhanVien() {
        initComponents();
        loadnv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupgt = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenv = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblma = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        lblhoten = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        lblngaysinh = new javax.swing.JLabel();
        jdcngaysinh = new com.toedter.calendar.JDateChooser();
        lblcccd = new javax.swing.JLabel();
        txtcccd = new javax.swing.JTextField();
        lbldiachi = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        lblsdt = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        lblgioitinh = new javax.swing.JLabel();
        lblchucvu = new javax.swing.JLabel();
        lbltaikhoan = new javax.swing.JLabel();
        txttaikhoan = new javax.swing.JTextField();
        lblmatkhau = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JTextField();
        cbbchucvu = new javax.swing.JComboBox<>();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        radnam = new javax.swing.JRadioButton();
        radnu = new javax.swing.JRadioButton();
        txtthongbao = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 540));

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        modelnv = new DefaultTableModel(new Object [][] {
        },
        new String [] {
            "STT", "Mã", "Họ Tên", "Ngày Sinh", "CCCD","Địa Chỉ", "SĐT", "Giới Tính","Tài khoản","Chức vụ"
        });
        tablenv.setModel(modelnv);
        tablenv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenv);
        if (tablenv.getColumnModel().getColumnCount() > 0) {
            tablenv.getColumnModel().getColumn(3).setResizable(false);
            tablenv.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txttimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntimkiem)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblma.setText("Mã:");

        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });

        lblhoten.setText("Họ Tên:");

        lblngaysinh.setText("Ngày Sinh:");

        lblcccd.setText("CCCD:");

        lbldiachi.setText("Địa chỉ:");

        lblsdt.setText("SĐT:");

        lblgioitinh.setText("Giới Tính:");

        lblchucvu.setText("Chức vụ:");

        lbltaikhoan.setText("Tài Khoản:");

        lblmatkhau.setText("Mật Khẩu:");

        cbbchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên Bán Hàng", "Người Quản Lý" }));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        buttonGroupgt.add(radnam);
        radnam.setText("Nam");

        buttonGroupgt.add(radnu);
        radnu.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txthoten))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblngaysinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcccd))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdiachi))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsdt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(radnam)
                                .addGap(18, 18, 18)
                                .addComponent(radnu))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbchucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbltaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttaikhoan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmatkhau))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblma))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhoten)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblngaysinh)
                    .addComponent(jdcngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcccd)
                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiachi)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsdt)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgioitinh)
                    .addComponent(radnam)
                    .addComponent(radnu))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblchucvu)
                    .addComponent(cbbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltaikhoan)
                    .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatkhau)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtthongbao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnsua))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void tablenvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenvMouseClicked
        // TODO add your handling code here:
    	int row = tablenv.getSelectedRow();
    	loadTbltoForm(row);
    }//GEN-LAST:event_tablenvMouseClicked

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
    	setEditableForm(true);
        them_nv();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroupgt;
    private javax.swing.JComboBox<String> cbbchucvu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radnam;
    private javax.swing.JRadioButton radnu;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcngaysinh;
    private javax.swing.JLabel lblcccd;
    private javax.swing.JLabel lblchucvu;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lblgioitinh;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblma;
    private javax.swing.JLabel lblmatkhau;
    private javax.swing.JLabel lblngaysinh;
    private javax.swing.JLabel lblsdt;
    private javax.swing.JLabel lbltaikhoan;
    private javax.swing.JTable tablenv;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttaikhoan;
    private javax.swing.JLabel txtthongbao;
    private javax.swing.JTextField txttimkiem;
    private DefaultTableModel modelnv;
    private NhanVien_DAO nv_dao = new NhanVien_DAO();
    private int stt = 0;
    private int check = 0;
    private void loadnv() {
        while(tablenv.getRowCount()!=0) {
			modelnv.removeRow(0);
		}
    	NhanVien_DAO nv = new NhanVien_DAO();
    	String gt;
    	ArrayList<NhanVien> dsnv = nv.getAllNV();
    	for (NhanVien nhanvien : dsnv) {
    		if(nhanvien.isGioiTinh()== false) {
    			gt = "Nữ";
    		}else
    			gt = "Nam";
			Object row[] = {++stt, nhanvien.getMaNV(), nhanvien.getHoTen(), nhanvien.getNgaySinh(), nhanvien.getCccd(),nhanvien.getDiaChi(),nhanvien.getSdt(), gt,null,nhanvien.getChucVu().getTenCV()};
			modelnv.addRow(row);
		}
    }
    public void loadTbltoForm(int row) {
        System.out.println(row);
		txtma.setText(tablenv.getValueAt(row, 1).toString());
		txthoten.setText(tablenv.getValueAt(row, 2).toString());
		java.util.Date ngaySinh = null;
		try {
			ngaySinh = new SimpleDateFormat("yyyy-MM-dd").parse(tablenv.getValueAt(row, 3).toString());
		} catch (Exception e) {
			// TODO: handle exception
		}
		jdcngaysinh.setDate(ngaySinh);
		txtcccd.setText(tablenv.getValueAt(row, 4).toString());
		txtdiachi.setText(tablenv.getValueAt(row, 5).toString());
		txtsdt.setText(tablenv.getValueAt(row, 6).toString());
		if (tablenv.getValueAt(row, 7).toString().equals("Nam"))
			radnam.setSelected(true);
		else
			radnu.setSelected(true);
		txttaikhoan.setText(tablenv.getValueAt(row, 8).toString());
		cbbchucvu.setSelectedItem(tablenv.getValueAt(row, 9));
		setEditableForm(true);
	}
    public void setEditableForm(boolean st) {
      txtma.setEditable(st);
      txthoten.setEditable(st);
      jdcngaysinh.setEnabled(st);
      txtcccd.setEditable(st);
      txtdiachi.setEditable(st);
      txtsdt.setEditable(st);
      radnam.setEnabled(st);
      radnu.setEnabled(st);
      cbbchucvu.setEnabled(st);
      txttaikhoan.setEnabled(st);
      txtmatkhau.setEnabled(st);
      
    }
    public void them_nv(){
        if(check != 1){
            btnxoa.setText("Huỷ");
            btnsua.setEnabled(false);
            check = 1;
        }else{
            checkThongTin();
            if(checkThongTin()){
                 String hoten = txthoten.getText();
                 String diachi = txtdiachi.getText();
                 String sdt = txtsdt.getText();
                 Boolean gt = radnam.isSelected() ? true : false;
                 Date ns = Date.valueOf(((JTextField) jdcngaysinh.getDateEditor().getUiComponent()).getText());
                 String cccd = txtcccd.getText();
                 String cv = cbbchucvu.getSelectedItem().toString();
                 ChucVu chucvu = new ChucVu(null, cv); 
                 NhanVien nv = new NhanVien(hoten, ns, cccd, diachi, gt, chucvu);
                		 try {
                    nv_dao.addNV(nv);
                } catch (Exception e) {
                    // TODO Auto-generated catch block
				e.printStackTrace();
                }
                modelnv.setRowCount(0);
                stt = 0;
                loadnv();
            }
        }
    
    // End of variables declaration//GEN-END:variables
    }
    //regest
    public boolean checkThongTin(){
        String ten = txthoten.getText();
        String dc = txtdiachi.getText();
        String sdt = txtsdt.getText();
        String today = Date.valueOf(LocalDate.now()).toString();        
        if(ten.equals("")){
                txtthongbao.setText("Nhập họ tên khách hàng");
                return false;
            }
        if(jdcngaysinh.getDate()==null){
        	txtthongbao.setText("Nhập ngày sinh khách hàng");
            return false;
            }
        if(dc.equals("")){
        	txtthongbao.setText("Nhập địa chỉ khách hàng");
                return false;
            }
        if(!sdt.matches("[0-9]{10}")){
        	txtthongbao.setText("SĐT phải đúng định dạng 0xxxxxxxxx");
                return false;
            }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ns = dateFormat.format(jdcngaysinh.getDate());
        int a = ns.compareTo(today);
                System.out.println(a);
        if(a > 0){
        	txtthongbao.setText("Ngày sinh phải bé hơn ngày hiện tại");
                        return false;
                    }
        return true;
    }
}