/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.TKDT_DAO;
import entity.ThongKeDoanhThu;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI DESKTOP
 */
public class GD_TKDT extends javax.swing.JPanel {

    /**
     * Creates new form GD_TKDT
     */
    public GD_TKDT() throws ParseException {
        initComponents();
        MyinitComponents();
        loadThongKeDoanhThu();
        VHH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKeDoanhThu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbbThongKe = new javax.swing.JComboBox<>();
        lbNgay = new javax.swing.JLabel();
        jdcNgay = new com.toedter.calendar.JDateChooser();
        lbTongSanPham = new javax.swing.JLabel();
        txtTongSanPham = new javax.swing.JTextField();
        txtTongHoaDon = new javax.swing.JTextField();
        lbTongHoaDon = new javax.swing.JLabel();
        lbDoanhThu = new javax.swing.JLabel();
        txtDoanhThu = new javax.swing.JTextField();
        lbSanPhamBanNhieuNhat = new javax.swing.JLabel();
        txtSanPhamBanNhieuNhat = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 476));

        tableThongKeDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Sản Phẩm", "Tổng Số Lượng"
            }
        ));
        jScrollPane1.setViewportView(tableThongKeDoanhThu);
        if (tableThongKeDoanhThu.getColumnModel().getColumnCount() > 0) {
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setMinWidth(100);
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống Kê Doanh Thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbbThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê theo ngày", "Thống kê theo tháng" }));
        cbbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThongKeActionPerformed(evt);
            }
        });

        lbNgay.setText("Ngày");

        jdcNgay.setDateFormatString("yyyy-MM-dd");

        lbTongSanPham.setText("Tổng sản phẩm:");

        txtTongSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSanPhamActionPerformed(evt);
            }
        });

        txtTongHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongHoaDonActionPerformed(evt);
            }
        });

        lbTongHoaDon.setText("Tổng hoá đơn:");

        lbDoanhThu.setText("Doanh thu:");

        txtDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuActionPerformed(evt);
            }
        });

        lbSanPhamBanNhieuNhat.setText("Sản phẩm bán nhiều nhất:");

        txtSanPhamBanNhieuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSanPhamBanNhieuNhatActionPerformed(evt);
            }
        });

        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongSanPham)
                            .addComponent(lbNgay)
                            .addComponent(cbbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongHoaDon)
                            .addComponent(lbDoanhThu)
                            .addComponent(lbSanPhamBanNhieuNhat))
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(120, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtTongSanPham)
                                .addComponent(txtTongHoaDon)
                                .addComponent(txtDoanhThu)
                                .addComponent(txtSanPhamBanNhieuNhat)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cbbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongSanPham)
                    .addComponent(txtTongSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongHoaDon)
                    .addComponent(txtTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDoanhThu)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbSanPhamBanNhieuNhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSanPhamBanNhieuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void MyinitComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKeDoanhThu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbbThongKe = new javax.swing.JComboBox<>();
        lbNgay = new javax.swing.JLabel();
        jdcNgay = new com.toedter.calendar.JDateChooser();
        lbTongSanPham = new javax.swing.JLabel();
        txtTongSanPham = new javax.swing.JTextField();
        txtTongHoaDon = new javax.swing.JTextField();
        lbTongHoaDon = new javax.swing.JLabel();
        lbDoanhThu = new javax.swing.JLabel();
        txtDoanhThu = new javax.swing.JTextField();
        lbSanPhamBanNhieuNhat = new javax.swing.JLabel();
        txtSanPhamBanNhieuNhat = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 476));

        modelThongKeDoanhThu = new DefaultTableModel(new Object [][]{
        },
        new String []{
            "STT", "Sản Phẩm", "Tổng Số Lượng"
        });
        tableThongKeDoanhThu.setModel(modelThongKeDoanhThu);
        jScrollPane1.setViewportView(tableThongKeDoanhThu);
        if (tableThongKeDoanhThu.getColumnModel().getColumnCount() > 0) {
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setMinWidth(100);
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableThongKeDoanhThu.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống Kê Doanh Thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbbThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê theo ngày", "Thống kê theo tháng" }));
        cbbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThongKeActionPerformed(evt);
            }
        });

        lbNgay.setText("Ngày");

        jdcNgay.setDateFormatString("yyyy-MM-dd");

        lbTongSanPham.setText("Tổng sản phẩm:");

        txtTongSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSanPhamActionPerformed(evt);
            }
        });

        txtTongHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongHoaDonActionPerformed(evt);
            }
        });

        lbTongHoaDon.setText("Tổng hoá đơn:");

        lbDoanhThu.setText("Doanh thu:");

        txtDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuActionPerformed(evt);
            }
        });

        lbSanPhamBanNhieuNhat.setText("Sản phẩm bán nhiều nhất:");

        txtSanPhamBanNhieuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSanPhamBanNhieuNhatActionPerformed(evt);
            }
        });

        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongSanPham)
                            .addComponent(lbNgay)
                            .addComponent(cbbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongHoaDon)
                            .addComponent(lbDoanhThu)
                            .addComponent(lbSanPhamBanNhieuNhat))
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(120, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtTongSanPham)
                                .addComponent(txtTongHoaDon)
                                .addComponent(txtDoanhThu)
                                .addComponent(txtSanPhamBanNhieuNhat)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cbbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongSanPham)
                    .addComponent(txtTongSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongHoaDon)
                    .addComponent(txtTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDoanhThu)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbSanPhamBanNhieuNhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSanPhamBanNhieuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }
    private void cbbThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThongKeActionPerformed

    private void txtTongSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSanPhamActionPerformed

    private void txtTongHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongHoaDonActionPerformed

    private void txtDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuActionPerformed

    private void txtSanPhamBanNhieuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSanPhamBanNhieuNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanPhamBanNhieuNhatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
//        Date ns = Date.valueOf(((JTextField) jdcNgay.getDateEditor().getUiComponent()).getText());
//        String today = Date.valueOf(LocalDate.now()).toString();  
//        System.out.println(today);
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

             String sd = dateFormat.format(jdcNgay.getDate());
             System.out.println(sd);
    }//GEN-LAST:event_btnThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbbThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgay;
    private javax.swing.JLabel lbDoanhThu;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbSanPhamBanNhieuNhat;
    private javax.swing.JLabel lbTongHoaDon;
    private javax.swing.JLabel lbTongSanPham;
    private javax.swing.JTable tableThongKeDoanhThu;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtSanPhamBanNhieuNhat;
    private javax.swing.JTextField txtTongHoaDon;
    private javax.swing.JTextField txtTongSanPham;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelThongKeDoanhThu;
    private TKDT_DAO tkdt_dao = new TKDT_DAO();
    private int stt = 0;
    private void loadThongKeDoanhThu() throws ParseException{
        while(tableThongKeDoanhThu.getRowCount()!=0) {
			modelThongKeDoanhThu.removeRow(0);
		}
//       Date ns = Date.valueOf(((JTextField)jdcNgay.getDateEditor().getUiComponent()).getText());
        int tongsp = 0;
        int shd = 0;
        double doanhthu = 0;
        String check ="" ;
        String bnn = "";
        int checkbnn = 0;
        TKDT_DAO tkdt = new TKDT_DAO();
        String today = Date.valueOf(LocalDate.now()).toString();  
        java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(today);
        jdcNgay.setDate(date2);
        ArrayList<ThongKeDoanhThu> dsTKDT = tkdt.getAllThongKeDoanhThu("2022-12-06");
        for (ThongKeDoanhThu tk : dsTKDT){
            Object row[] = {++stt, tk.getTenSP(), tk.getTongSoLuong()};
            modelThongKeDoanhThu.addRow(row);
            tongsp = tongsp + tk.getTongSoLuong();
            if (!check.equals(tk.getMaHD())) {
                shd++;
                check = tk.getMaHD();
            } else {
                check = tk.getMaHD();
            }
            
            doanhthu =doanhthu + Double.valueOf(tk.getTongSoLuong())*tk.getGiaBan();
            
            if(tk.getTongSoLuong() > checkbnn){
                bnn = tk.getTenSP();
            }
        }
        String tongSL = String.valueOf(tongsp);
        String tongHD = String.valueOf(shd);
        String tongDoanhThu = String.valueOf(doanhthu);
        txtTongSanPham.setText(tongSL);
        txtTongHoaDon.setText(tongHD);
        txtDoanhThu.setText(tongDoanhThu);
        txtSanPhamBanNhieuNhat.setText(bnn);
    }
    
    public void VHH(){
        txtTongSanPham.setEditable(false);
        txtTongHoaDon.setEditable(false);
        txtDoanhThu.setEditable(false);
        txtSanPhamBanNhieuNhat.setEditable(false);
    }
}
